// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SalesManagementContext))]
    [Migration("20250215212629_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("NOME");

                    b.Property<int>("Quantity")
                        .HasColumnType("INT")
                        .HasColumnName("QUANTIDADE");

                    b.Property<long>("SalesId")
                        .HasColumnType("BIGINT")
                        .HasColumnName("ID_VENDA");

                    b.Property<decimal>("TotalValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(19,5)")
                        .HasColumnName("VALOR_TOTAL");

                    b.Property<decimal>("UnitValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(19,5)")
                        .HasColumnName("VALOR_UNITARIO");

                    b.HasKey("ProductId");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Sales", b =>
                {
                    b.Property<int>("SalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID_VENDA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalesId"));

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("CLIENTE");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATETIME")
                        .HasColumnName("DATA");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(19,5)")
                        .HasColumnName("VALOR_VENDA");

                    b.HasKey("SalesId");

                    b.ToTable("VENDA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
